apiVersion: v1
kind: Service
metadata:
  name: oficina-api-service
  namespace: oficina
spec:
  selector:
    app: oficina-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort
